#!/usr/bin/env bash

tmppic="/tmp/wallpic"
WALLPAPER_DIR="$HOME/Pictures/Wallpapers/tuff" 
WALL="$HOME/Pictures/Wallpapers/landschaften" 
NEW="$HOME/Pictures/Wallpapers/newabm" 

while : 
do
    find "$WALLPAPER_DIR" "$WALL" "$NEW" \
        -type f \
        -print0 |
    shuf -z |
    while IFS= read -r -d '' WALLPAPER; do
        echo "$WALLPAPER"
        ~/.config/hypr/scripts/wal.sh "$WALLPAPER"
        sleep 900
    done
done 
