#!/usr/bin/env bash

tmppic="/tmp/wallpic"
WALLPAPER_DIR="$HOME/Pictures/Wallpapers/tuff" 
WALL="$HOME/Pictures/Wallpapers/landschaften" 
NEW="$HOME/Pictures/Wallpapers/newabm" 

while : 
do
    CURRENT_WALL=$(cat "$tmppic")

    # Get a random wallpaper that is not the current one
    WALLPAPER=$(find "$WALLPAPER_DIR" "$WALL" -type f ! -name "$(basename "$CURRENT_WALL")" | shuf -n 1)
    echo "$WALLPAPER" > $tmppic
    echo "$WALLPAPER"

    # Apply the selected wallpaper
    ~/.config/hypr/scripts/wal.sh "$WALLPAPER"
    
    sleep 900
done 
