#monitor = DP-3, 2560x1440@180, 1920x0, 1, bitdepth, 10, cm, hdr



#Erster
monitor = DP-3, 2560x1440@180, 1920x0, 1
#monitor = DP-3, disable

#setze den primären X11-monitor. spiele sollten mit der Auflösung von dem hauptmonitor starten
exec-once= xrandr --output DP-3 --primary


#Zweiter
monitor = DP-1, 1920x1080@60 , 0x0, 1
#monitor = DP-1, disable



#Fernseher
monitor = HDMI-A-1, disable
