
profile {
    time = 07:00
    identity = true           # Normales Tageslicht, keine Farbfilter
}

profile {
    time = 19:00
    temperature = 6000        # Warmer, abendlicher Farbton
    gamma = 0.8               # Bildschirm wird etwas dunkler
}

