source = ~/.cache/wal/colors-hyprland.conf

$accent = $color5
$accentAlpha = $color5
$font = JetBrainsMono Nerd Font
$red = rgb(f38ba8)

# GENERAL
general {
  hide_cursor = true
  ignore_empty_input = true
}

# BACKGROUND
background {
  monitor =
  #path = $HOME/Pictures/Wallpapers/metropolis.png
  path = screenshot
  blur_passes = 4
  blur_size = 1
  #brightness = 5
  #noise = 1
  color = $background
}

# LAYOUT
label {
  monitor = DP-3
  text = Layout: $LAYOUT
  color = $color5
  font_size = 25
  font_family = $font
  position = 30, -30
  halign = left
  valign = top
}

# TIME
label {
  monitor = DP-3
  text = $TIME
  color = $color5
  font_size = 90
  font_family = $font
  position = -30, 0
  halign = right
  valign = top
}

# DATE
label {
  monitor = DP-3
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = $color5
  font_size = 25
  font_family = $font
  position = -30, -150
  halign = right
  valign = top
}
# UPTIME
label {
    monitor = DP-3
    text = cmd[update:60000] /bin/bash -c 'uptime -p | sed "s/up //"'
    color = $color5
    font_size = 16
    font_family = $font
    position = -50, 80
    halign = right
    valign = bottom
}
# FINGERPRINT
{
  monitor = DP-3
  text = $FPRINTPROMPT;
  color = $color5;
  font_size = 14;
  font_family = $font;
  position = "0, -107";
  halign = "center";
  valign = "center";
}

# USER AVATAR
image {
  monitor = DP-3
  path = $HOME/.face
  size = 100
  border_color = $accent
  position = 0, 75
  halign = center
  valign = center
}

# INPUT FIELD
input-field {
  monitor = DP-3
  size = 300, 60
  outline_thickness = 4
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = $accent
  inner_color = $background
  font_color = $color5
  fade_on_empty = false
  #placeholder_text = <span foreground="##$color5"><i>󰌾 Logged in as </i><span foreground="##$accentAlpha">$USER</span></span>
  placeholder_text = 󰌾 Logged in as $USER
  hide_input = false
  check_color = $accent
  fail_color = $red
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $yellow
  position = 0, -47
  halign = center
  valign = center
}
