#clipboard manager
exec-once = wl-clip-persist --clipboard regular

exec-once = hypridle

#Wallpaper
exec-once = hyprpaper

#Waybar
exec-once = waybar

#hyprsunset
exec-once = hyprsunset

#plugins laden
exec-once = hyprpm reload -n

#starte sansa-socket
exec-once = socat UNIX-LISTEN:/tmp/usb.sock,fork EXEC:/home/mathis/.local/bin/sansa/sansawrapper.sh

# System Trays
exec-once = systemctl --user start systray
exec-once = systemctl --user start vpntray

