#polkit agent
exec-once=/usr/lib64/hyprpolkitagent/hyprpolkitagent

# hyprlang if ARTIX
    exec-once = runsvdir ~/service 
    exec-once = sway-audio-idle-inhibit
# hyprlang endif

exec-once = /usr/lib/xdg-desktop-portal-termfilechooser -r

#clipboard manager
exec-once = wl-clip-persist --clipboard regular

exec-once = hypridle

#Wallpaper
exec-once = hyprpaper
exec-once = ~/.config/hypr/scripts/gut.sh

#hyprsunset
exec-once = hyprsunset

#plugins laden
exec-once = hyprpm reload

# hyprlang if !ARTIX
#starte sansa-socket
    exec-once = socat UNIX-LISTEN:/tmp/usb.sock,fork EXEC:/home/mathis/.local/bin/sansa/sansawrapper.sh
    exec-once = sleep 5 && wl-screenrec --audio -f /tmp/screenrec.mkv -o DP-3 --history 300
# hyprlang endif
