#polkit agent
exec-once=/usr/lib64/hyprpolkitagent/hyprpolkitagent

# hyprlang if ARTIX
    #start pipewire and wireplumber
    exec-once = ~/.config/hypr/scripts/start-audio.sh
    #Waybar -- moved to systemd-service funzt nicht die kacke
    exec-once = sleep 1.5 && waybar -l trace > ~/WAYBAR_LOG 2>&1
# hyprlang endif

exec-once = /usr/lib/xdg-desktop-portal-termfilechooser -r

#clipboard manager
exec-once = wl-clip-persist --clipboard regular

exec-once = hypridle

#Wallpaper
exec-once = hyprpaper
exec-once = ~/.config/hypr/scripts/hyprpaper-random


#hyprsunset
exec-once = hyprsunset

#plugins laden
exec-once = hyprpm reload -n

# hyprlang if !ARTIX
#starte sansa-socket
    exec-once = socat UNIX-LISTEN:/tmp/usb.sock,fork EXEC:/home/mathis/.local/bin/sansa/sansawrapper.sh
# hyprlang endif
