gesture = 3, horizontal, workspace
gesture = 3, down, mod: ALT, close
gesture = 3, up, special, music
gesture = 3, down, special, scrap
gesture = 2, swipe, mod: Super, resize
#gesture = 3, lspecial, musiceft, scale: 1.5, float
