misc{
    swallow_regex = ^(Alacritty|kitty|foot)$
        middle_click_paste = false
        enable_swallow = true
        focus_on_activate = true
    session_lock_xray = true
    render_unfocused_fps = 60
}
