windowrule = match:class org.pulseaudio.pavucontrol, float true, size monitor_w/1.5 monitor_w/2.5 
windowrule = match:title termfilechooser, float true, size monitor_w/1.5 monitor_w/2.5 
windowrule = match:title wiremix, float true, size monitor_w/1.5 monitor_w/2.5 
windowrule = match:title bluetui, float true, size monitor_w/1.5 monitor_w/2.5 
windowrule = match:title qalc, float true, size monitor_w/1.5 monitor_w/2.5 
